# make it explicit that we favor the new container-based travis workers
sudo: false

language: python
python:
  - 2.7
# Pre-install packages for the ubuntu distribution
cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
addons:
  apt:
    packages:
      - libfftw3-dev
      - libfftw3-3
      - libatlas3gf-base
      - libatlas-dev
      - gfortran
      - libgfortran3
      - eigen3
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir
    - MODULE=protoclass
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - USERNAME="glemaitre"
    - DOC_REPO="protoclass-docs"
    - PROJECT="protoclass"
    - EMAIL="g.lemaitre58@gmail.com"
    - DOC_URL=""
    - secure: "parXNeGzbuyg9nLd8sfyk+vYSQEMOVCL7qCFlWvvAFm3JDUU/UG1YEBKud0bkZqyhvD8CGP4IIZ2t09J4zw+757sW7+bPrZamkQppTset411ybbt7AIsU+6io0e6NNKoM91BumoufAIZy+z8VcK8o5H+6ihJsdtTL71y+VZLXguTlo3uXUj8RlGi00rCd4N6cwGQi7uSgQnZLa1ijs9sVKklmY8F75po9TLNJWgPb0AqfZ0hqEHvSE9Yq8jTyCPsOPASuoH48FwqHAiv1gx4L0JGBU9v6zb9vRzPj7vbcZBrZqLRAlHvCNmv+XKspFkNE3d8vxUWMNn5uzZbQ5vi/5pAhhJM4eY88OhcQuIDc3HjRdJK65WCw+jDpxIxfgsQyqvPsal7hk/u8SghW6kbqtx0dYdwayLT0/dC4Nhe4iIXsHX8bXBgvtD7nTmfGJBTcl8SjnZ4egc59edxe5V/xC47C0FGayNMRR8HP4Crzs7nOS3t0zL9hoEf6OVM+DAPIRkzwu2wPK8hKET6S7Csta8as1cvKYzYf4hdyMWPGEOOpiuFhiKDaEBJa8hC2ASFgil4kjvQc0ujuU4frxk+oZbmFqgRRIsP12uFBsp7TUHzsLgXljODmzoEqs9Ntz/bBlqZf1ONNEt9pQkDuxT0bYLac1UVKauxG9Sp3B9VEmI="

  matrix:
    # This environment tests the using anaconda
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
      NUMPY_VERSION="1.10.0" SCIPY_VERSION="0.17.0"

before_install:
  - git submodule update --init --recursive
install:
  - travis_wait 30
  - source build_tools/travis/install.sh
script: 
  - bash build_tools/travis/push_doc.sh
  - bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
